### ISSUE TITLE
Command not supported in AtlasDB

### ISSUE THREAD

**Issue by geraldoantonio** [andrewmolyuk/mongo-leader#167]
https://github.com/andrewmolyuk/mongo-leader/blob/2a4fde0644111b597c60acf9d7b0c406962a5107/index.js#L26

MongoServerError: (Unauthorized) not authorized on admin to execute command { setParameter: 1, ttlMonitorSleepSecs: 1, ... , $db: "admin" }

https://www.mongodb.com/docs/atlas/unsupported-commands/

**Comment by geraldoantonio** [comment]
Other option for ignore:

```
    try {
      await this.db.admin().command({ setParameter: 1, ttlMonitorSleepSecs: 1 })
    } catch (_e) {
      console.error('Failed running setParameter ttlMonitorSleepSecs: 1')
    }
```

**Comment by andrewmolyuk** [comment]
Fixed by https://github.com/andrewmolyuk/mongo-leader/pull/168
