### ISSUE TITLE
Doesn't dropCollection delete the current leader?

### ISSUE THREAD

**Issue by Legion2** [andrewmolyuk/mongo-leader#36]
The following is called when creating the leader election. Doesn't this delete the information about the current leader if there is already one?

https://github.com/andrewmolyuk/mongo-leader/blob/0e0b52035fe2a05434776bdb0cf5c74fa8876056/index.js#L21

**Comment by andrewmolyuk** [comment]
Fixed by the following commit - https://github.com/andrewmolyuk/mongo-leader/commit/4e783c66841e8305d702a1470651ea10d12678ea#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346
